### PR TITLE
Task/ci local

### PR DESCRIPTION
**Pull request by nikodembernat**
I don't know whether lucide-icons/lucide-flutter will allow any updates, so I will just run CI on my fork.

### CODE REVIEW

**Comment by abdullah-cse** [comment]
Hello, @n-bernat thanks for your PR. I'm also using LucideIcon on my project. But now they don't maintain it anymore. Will you publish it on [PUB](https://pub.dev) like Lucide_Icon_Plus, or Lucide_Icon_Community etc naming??

**Comment by nikodembernat** [comment]
> Hello, @n-bernat thanks for your PR. I'm also using LucideIcon on my project. But now they don't maintain it anymore. Will you publish it on [PUB](https://pub.dev) like Lucide_Icon_Plus, or Lucide_Icon_Community etc naming??


Hi, I'm in contact with the Lucile team on discord and hopefully they will either merge my PR or give me access to their package, so I can maintain it

**Comment by nikodembernat** [comment]
I would rather avoid creating another package, because there are lots of packages with weird names in the Flutter ecosystem, and I would prefer to fight that instead of creating another one like that

**Comment by abdullah-cse** [comment]
> > Hello, @n-bernat thanks for your PR. I'm also using LucideIcon on my project. But now they don't maintain it anymore. Will you publish it on [PUB](https://pub.dev) like Lucide_Icon_Plus, or Lucide_Icon_Community etc naming??
> 
> Hi, I'm in contact with the Lucile team on discord and hopefully they will either merge my PR or give me access to their package, so I can maintain it

That's will be great.❤️❤️❤️

**Pull request merged**
